.PHONY: clean All

All:
	@echo "----------Building project:[ FirstProgramm - Debug ]----------"
	@cd "FirstProgramm" && "$(MAKE)" -f  "FirstProgramm.mk"
clean:
	@echo "----------Cleaning project:[ FirstProgramm - Debug ]----------"
	@cd "FirstProgramm" && "$(MAKE)" -f  "FirstProgramm.mk" clean
